volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

services:
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: bankapp-auth-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-password}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  db:
    image: postgres:15-alpine
    container_name: bankapp-auth-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: bankapp-auth-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
#    command: redis-server --requirepass ${REDIS_PASSWORD}
#    ports:
#      - "${REDIS_PORT}:6379"
#    volumes:
#      - redis_data:/data

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: bankapp-auth-service
#    restart: unless-stopped
#    environment:
#      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
#      DB_URL: db
#      DB_PORT: 5432
#      DB_SCHEMA: ${DB_SCHEMA}
#      DB_USERNAME: ${DB_USERNAME}
#      DB_PASSWORD: ${DB_PASSWORD}
#      REDIS_HOSTNAME: redis
#      REDIS_PASSWORD: ${REDIS_PASSWORD}
#      REDIS_PORT: 6379
#      SESSION_NAMESPACE: ${SESSION_NAMESPACE}
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#      - redis
#    networks:
#      - bankapp-network