volumes:
  postgres_data:
  redis_data:

networks:
  bankapp-network:
    driver: bridge

services:
  db:
    image: postgres:15-alpine
    container_name: bankapp-auth-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bankapp-network

  redis:
    image: redis:7-alpine
    container_name: bankapp-auth-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - bankapp-network

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: bankapp-auth-service
#    restart: unless-stopped
#    environment:
#      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
#      DB_URL: db
#      DB_PORT: 5432
#      DB_SCHEMA: ${DB_SCHEMA}
#      DB_USERNAME: ${DB_USERNAME}
#      DB_PASSWORD: ${DB_PASSWORD}
#      REDIS_HOSTNAME: redis
#      REDIS_PASSWORD: ${REDIS_PASSWORD}
#      REDIS_PORT: 6379
#      SESSION_NAMESPACE: ${SESSION_NAMESPACE}
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#      - redis
#    networks:
#      - bankapp-network