spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    # Connection pool settings
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
  # JPA / Hibernate settings
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        '[show_sql]': false
        '[format_sql]': true
        '[globally_quoted_identifiers]': true
#  data:
#    redis:
#      host: ${REDIS_HOSTNAME:localhost}
##      password: ${REDIS_PASSWORD}
#      port: ${REDIS_PORT:6379}
#  session:
#    redis:
#      flush-mode: on_save
#      namespace: ${SESSION_NAMESPACE}
logging:
  level:
    org.springframework.security: DEBUG
    online.bankapp.authservice: TRACE
