CREATE TABLE my_credential_record
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    credential_id            BYTEA                                   NOT NULL,
    counter                  BIGINT                                  NOT NULL,
    attestation_statement    BYTEA,
    client_data              BYTEA,
    attested_credential_data BYTEA,
    transports               VARCHAR                                 NOT NULL,
    uv_initialized           BOOLEAN                                 NOT NULL,
    backup_eligible          BOOLEAN                                 NOT NULL,
    backed_up                BOOLEAN                                 NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    last_used                TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_mycredentialrecord PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE my_credential_record
    ADD CONSTRAINT uc_mycredentialrecord_credentialid UNIQUE (credential_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);