CREATE TABLE passkeys
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    credential_id                BYTEA                                   NOT NULL,
    credential_type              VARCHAR                                 NOT NULL,
    public_key                   BYTEA                                   NOT NULL,
    transports                   VARCHAR,
    uv_initialized               BOOLEAN,
    backup_eligible              BOOLEAN,
    backup_state                 BOOLEAN,
    user_entity_user_id          BYTEA                                   NOT NULL,
    attestation_object           BYTEA,
    attestation_client_data_json BYTEA,
    label                        VARCHAR(255),
    last_used                    TIMESTAMP WITHOUT TIME ZONE,
    created                      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    signature_count              BIGINT,
    CONSTRAINT pk_passkeys PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

CREATE UNIQUE INDEX idx_credential_id ON passkeys (credential_id);

CREATE INDEX idx_user_entity_user_id ON passkeys (user_entity_user_id);